name: Generate Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'  # tous les jours à minuit
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ENNDRAKKO
          outputs: |
            snake.svg
